language: python
python:
    - 3.8

services:
    - docker

before_script:
    - pip install coverage
    - mkdir shared

script:
    - docker-compose run -v "$PWD/shared:/shared" application

after_success:
    - bash <(curl -s https://codecov.io/bash)
