language: python
python:
    - 3.8

services:
    - docker

before_script:
    - pip install coverage
    - ci_env=`bash <(curl -s https://codecov.io/env)`

script:
    - docker-compose run $ci_env application
