version: 1.0.{build}

branches:
  only:
    - master

  except:
    - tests

skip_tags: true

skip_non_tags: true

skip_commits:
  message: /.*\.(png|jpg|jpeg|bmp|gif|md|txt)/      # Regex for matching commit message

build: off

