version: 1.0.{build}

branches:
  only:
    - master

  except:
    - tests

skip_tags: true

skip_non_tags: true

skip_commits:
  message: /.*\.(png|jpg|jpeg|bmp|gif|md|txt)/      # Regex for matching commit message

services:
  - docker

build: off

image:
  - Visual Studio 2017

hosts:
  localhost: 127.0.0.1

before_test:
  - dir

test_script:
  - cmd: docker-compose run %ci_env% test_app
