version: '3.7'

services: 
    db:
        image: postgres
        volumes: 
            - ./application/sources/database/:/docker-entrypoint-initdb.d/
        environment:
            - POSTGRES_DB=CatsQMS
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345qwerty
    
    application:
        build: .
        command: sh -c './wait-for db:5432 -- start_app'
        ports:
            - "8080:8080"
        depends_on:
            - db

    test:
        build: .
        command: >
            bash -c "./wait-for db:5432 -- coverage run -m unittest discover application/tests
            && bash <(curl -s https://codecov.io/bash)"
        depends_on:
        - db